---
output: 
  pdf_document:
    latex_engine: xelatex
    template: cv-latex.tex
geometry: margin=.7in

#bibliography: citations.bib
#nocite: '@*'

title: "Curriculum Vitae"
author: Cristian Rohr
name: Cristian
lastname: Rohr
jobtitle: Bioinformático 
address: Your address

fontawesome: yes
email: your_mail - your_mail
github: your_github
linkedin: cristianrohrbio
twitter: your_twitter
phone: "+55 55555555"
web: cristianrohr.github.io
updated: no

keywords: Data Science, Bioinformatics

fontsize: 10pt # Valores validos entre 10 y 12pt
urlcolor: NavyBlue
---

# Experiencia Profesional 

\textbf{\textcolor{coolblack} {Líder Bioinformática}} | \textbf{Héritas, Rosario, Argentina} \hfill \textcolor{mygray} {Oct. 2018 - Actualidad}

\textbf{\textcolor{coolblack} {Analista Bioinformático}} | \textbf{Héritas, Rosario, Argentina} \hfill \textcolor{mygray} {May 2016 - Sep. 2018}

- En Héritas mi tarea principal como analista bioinformático fue el desarrollo e implementación de los algoritmos y modelos predictivos del test prenatal no invasivo [Héritas VISION](http://heritas.com.ar/genomica-de-la-reproduccion/vision/), y del test de microbioma intestinal [Héritas MicroXplora](http://heritas.com.ar/microxplora/). Además de estar fuertemente involucrado en el desarrollo de herramientas en Shiny/R para automatizar tareas y asistir a los análistas genéticos, en diversos productos como el test de biopsías líquidas [Héritas OncoSens](http://heritas.com.ar/genomica-clinica/oncosens/), [Héritas Focus](http://heritas.com.ar/genomica-clinica/exoma-clinico/), [Héritas CLEAR](http://heritas.com.ar/genomica-clinica/cancer-hereditario/)
- Diseño, desarrollo, implementación y mantenimiento de los pipelines de análisis en un entorno de computo de alto rendimiento para la entrega de resultados en tiempo y forma.

\textbf{\textcolor{coolblack} {Analista Bioinformático}} | \textbf{INDEAR/Héritas, Rosario, Argentina} \hfill \textcolor{mygray} {May 2016 - Sep. 2018}

- Desarrollo y mantenimiento de pipelines bioinformáticos para diversas aplicaciones de I+D internas de la empresa. Entre ellos: metagenómica
16S, RNAseq, ensamblado de genomas bacterianos, genotipado por secuenciación.
- Asesoramiento y análisis de datos para usuarios de la plataforma de Genómica y Bioinformática de INDEAR.
- Análisis de secuencias de inserción en eventos transgénicos para su desregulación en mercados internacionales.

# Educación

\textbf{\textcolor{coolblack} {M.Sc. Ciencia de Datos e Ingeniería de Computadores}} | \textbf{Universidad de Granada (España)} \hfill \textcolor{mygray} {2018 - En curso}

- Especialidad: Ciencia de Datos y Tecnologías Inteligentes.


\textbf{\textcolor{coolblack} {Licenciado en Bioinformática}} | \textbf{Universidad de Entre Ríos (Argentina)} \hfill \textcolor{mygray} {2006 - 2010}

- Promedio: 7.93
- Tesis: "Identificación de genes candidatos implicados en la mantención del estado de pluripotencialidad de
células madre embrionarias usando métodos bioinformáticos". Calificación: 10 (Sobresaliente)


# Experiencia Académica

\textbf{\textcolor{coolblack} {Facultad de Ciencias Exactas y Naturales}} | \textbf{Universidad de Buenos Aires, Argentina} \hfill \textcolor{mygray} {Abril 2013 - Abril 2016}

- **Laboratorio de Genómica Médica y Evolución.**
- Colaboración en proyectos de investigación e I+D con diversas instituciones del ámbito público y privado.
- Desarrollo e implementación de bases de datos y servidores web para el análisis/visualización de datos obtenidos con paneles de secuenciación de tecnologías Ion Torrent de Life Technologies.
- Desarrollo de paneles personalizados para el screening de enfermedades humanas.

\textbf{\textcolor{coolblack} {Facultad de Ciencias Exactas y Naturales}} | \textbf{Universidad de Buenos Aires, Argentina}  \hfill \textcolor{mygray} {Sept. 2011 - Marzo 2013}

- **Laboratorio de Agrobiotecnología.**
- Participe en diversos proyectos del laboratorio como ser RNAseq y creación de bases de datos.
- Implementación de soluciones bioinformáticas para actividades rutinarias desarrolladas en el laboratorio.


# Docencia

\textbf{\textcolor{coolblack} {Jefe de Trabajos Prácticos}}. \textbf{Universidad de Buenos Aires, Argentina}. _Curso de posgrado: "Genómica de poblaciones y enfermedades”._ Departamento de Ecología, Genética y Evolución, FCEyN. \hfill \textcolor{mygray} {2015}.

\textbf{\textcolor{coolblack} {Jefe de Trabajos Prácticos}}. \textbf{Universidad de Buenos Aires, Argentina}. _Curso de posgrado “Genómica humana: variación, adaptación y poblaciones”._ Departamento de Ecología, Genética y Evolución, FCEyN. \hfill \textcolor{mygray} {2014}.

\textbf{\textcolor{coolblack} {Docente Invitado}}. \textbf{RSG Argentina}. _Curso ”Perl y Bioperl aplicado en Bioinformática”_. \hfill \textcolor{mygray} {2012}.

# Becas obtenidas
\textbf{\textcolor{coolblack} {Programa BEC.AR}}. \textbf{Ministerio de Educación.}. _Beca de Maestría en Ciencia y Tecnología para profesionales argentinos en el Reino de España_. \hfill \textcolor{mygray} {2018}.

\textbf{\textcolor{coolblack} {Beca interna doctoral para temas estratégicos}}. \textbf{CONICET}. _Laboratorio de Genómica Médica y Evolución - Instituto de Ecología, Genética y Evolución de Buenos Aires_. Director: Dr. Hernan Dopazo. \hfill \textcolor{mygray} {2013}.

\textbf{\textcolor{coolblack} {Beca Inicial en el Área de Bioinformática}}. \textbf{MINCyT-CYTED}.
_En el marco del Proyecto Genoma (MINCyT-CYTED). “Determinación del genoma del frijol, Phaseolus vulgaris L., para el aprovechamiento de los recursos naturales de Iberoamérica”._ Director: Dr. Alejandro Mentaberry. Laboratorio de Agrobiotecnología. FCEyN - UBA. \hfill \textcolor{mygray} {2011}.

# Premios y Distinciones

\textbf{\textcolor{coolblack} {Diploma de Honor}}. \textbf{Concejo Municipal de Rosario}. En reconocimiento a su trascendental tarea para acelerar la detección de distintas enfermedades a partir de métodos bioquímicos, biotecnológicos y genéticos. \hfill \textcolor{mygray} {2018}.

\textbf{\textcolor{coolblack} {Third position Best Poster Award}}. \textbf{ISCB - LA - 2016.}. Using oxford nanopore minion technology to deeply explore metagenome functions in the argentine human microbiome dataset characterized by illumina 16s metagenomics pipeline. \hfill \textcolor{mygray} {2016}.

# Publicaciones seleccionadas
### Revistas internacionales con referato
- Carlos J Pirola, Diego Flichman, Hernán Dopazo, Tomas Fernández Gianotti, Julio San Martino, **Cristian Rohr**, Martin Garaycoechea, Carla Gazzi, Gustavo O Castaño, Silvia Sookoian A Rare Nonsense Mutation in the Glucokinase Regulator Gene Is Associated With a Rapidly Progressive Clinical Form of Nonalcoholic Steatohepatitis. Hepatol Commun. 2018;2(9):1030-1036.
- Gosso MF, **Rohr C**, Brun B, et al. Exome-first approach identified novel INDELs and gene deletions in Mowat-Wilson Syndrome patients. Hum
Genome Var. 2018;5:21.
- Sookoian S, **Rohr C**, Salatino A, et al. Genetic variation in long noncoding RNAs and the risk of nonalcoholic fatty liver disease. Oncotarget.
2017 Feb 11. doi: 10.18632/oncotarget.15286.
- Silvia Sookoian, Diego Flichman, Romina Scian, **Cristian Rohr**, Hernán Dopazo, Tomas Fernández Gianotti, Julio San Martin, Gustavo O Castaño, Carlos J Pirola. Mitochondrial genome architecture in non-alcoholic fatty liver disease. J Pathol. 2016;240(4):437-449.
- Monzon, A; **Rohr, C**; Formasari, MS; Parisi, G. CoDNaS 2.0: a comprehensive database of protein conformational diversity in the native state.
Database (Oxford). 2016. DOI:10.1093/database/baw038.
- Sookoian S, Castaño GO, Scian R, Fernández Gianotti T, Dopazo H, **Rohr C**, Gaj G, San Martino J, Sevic I, Flichman D, Pirola CJ. Serum aminotransferases in nonalcoholic fatty liver disease are a signature of liver metabolic perturbations at the amino acid and Krebs cycle level. Am J
Clin Nutr. 2016 Feb;103(2):422-34. doi: 10.3945/ajcn.115.118695
- Parra RG*, Rohr CO*, Koile D, Perez-castro C, Yankilevich P. INSECT 2.0: a web-server for genome-wide cis-regulatory modules prediction.
Bioinformatics. 2015 Dec 12. pii: btv726. * Joint first author
- Pirola CJ, Scian R, Gianotti TF, Dopazo H, **Rohr C**, Martino JS, Castaño GO, Sookoian S. Epigenetic Modifications in the Biology of Nonalcoholic
Fatty Liver Disease: The Role of DNA Hydroxymethylation and TET Proteins. Medicine (Baltimore).2015;94(36):e1480. doi: 10.1097/MD.0000000000001480.
- **Rohr CO**, Levin LN, Mentaberry AN, Wirth SA. A first insight into Pycnoporus sanguineus BAFC 2126 transcriptome. PLoS ONE. 2013;8(12):e81033.
- Rohr CO*, Parra RG*, Yankilevich P, Perez-castro C. INSECT: IN-silico SEarch for Co-occurring Transcription factors. Bioinformatics. 2013;29(22):2852-8.
*Joint first author.

### Revistas Nacionales
- Vázquez M, Rohr C, Brun B, Grisolia M, Méjico M, Gosso MF, Fay F. Desarrollo del primer Ensayo Prenatal no Invasivo (NIPT) en Argentina. Informe ALAC, Año XXII N°1 2017, páginas 5-13.

# Presentaciones en congresos

\textbf{\textcolor{coolblack} {Héritas VISION: The challenge to develop the first Non Invasive Prenatal Testing (NIPT) Platform in Posadas-Misiones, Argentina}}. \textbf{Oral - Poster}. _8vo Congreso Argentino de Bioinformática y Biología Computacional (8CA2BC)_. 26-29 de Argentina Noviembre de 2017. Posadas, Misiones, Argentina.

\textbf{\textcolor{coolblack} {Using Oxford Nanopore MinION technology to deeply explore metagenome functions in the Argentine Human microbiome dataset characterised by Illumina 16s metagenomics pipeline}}. \textbf{Poster}. _Fourth International Society for Computational Biology Latin America Bioinformatics Conference (ISCB-LA) and the 7th Argentinian Congress of Bioinformatics and Computational Biology (CAB2C)_. 21-23 November 2016. Buenos Aires, Argentina.

\textbf{\textcolor{coolblack} {INSECT: Una herramienta para descomponer redes complejas de regulación génica}}. \textbf{Oral}. _1er Encuentro de estudiantes de bioinformática y biología computacional_. 25 y 26 de Noviembre de 2014. Fundación Instituto Leloir. Buenos Aires, Argentina.

\textbf{\textcolor{coolblack} {A Web Server for the Standardization of Molecular Diagnosis of Huntington’s Disease in Latin America}}. \textbf{Poster}. _IV Argentinean Conference on Computational Biology and Bioinformatics & the IV Conference of the Iberoamerican Society for Bioinformatics (SOIBIO)_. 29 al 31 de Octubre de 2013, CIFASIS-CONICET. Rosario, Argentina.

\textbf{\textcolor{coolblack} {INSECT: IN-silico SEarch for Co-occurring Transcription factors}}. \textbf{Poster}. _IV Argentinean Conference on Computational Biology and Bioinformatics & the IV Conference of the Iberoamerican Society for Bioinformatics (SOIBIO)_. 29 al 31 de Octubre de 2013, CIFASIS-CONICET. Rosario, Argentina.

\textbf{\textcolor{coolblack} {Bioinformatics annotation of Pycnoporus sanguineus BAFC 2126 transcriptome}}. \textbf{Oral}. _IV Argentinean Conference on Computational Biology and Bioinformatics & the IV Conference of the Iberoamerican Society for Bioinformatics (SOIBIO)_. 29 al 31 de Octubre de 2013, CIFASIS-CONICET. Rosario, Argentina.

\textbf{\textcolor{coolblack} {Development of a bioinformatics strategy to search for genes involved in specific metabolic Pathways: The case of ESCs}}. \textbf{Poster}. 

- _Simposio “Fronteras en Biociencias”_. 22 al 25 de abril 2012. Polo científico tecnológico. Buenos Aires. Argentina.
- _Segundo Congreso de la Asociación Argentina de Bioinformática y Biología Computacional_. 11 al 13 de mayo 2011. Facultad de Ingeniería de la Universidad Católica de Córdoba. Cordoba, Argentina.


# Visitas Científicas
\textbf{\textcolor{coolblack} {Proyecto DEANN de la convocatoria IRSES (Programa Marie Curie PIRSES-GA-2013-612583) del Séptimo Programa Marco de la Comisión Europea}}.  

- \textbf{Universitat Pompeu Fabra}. 2 meses en el Departamento de Ciencias Experimentales y de la Salud. Referencia Dr. Arcadi Navarro. Barcelona - España. 2014.
- \textbf{Centro de Investigación Príncipe Felipe}. 1 semana en el Laboratorio de Genética Computacional. Referencia Dr. Joaquín Dopazo. Valencia - España. 2014.

# Habilidades Técnicas
- **Lenguajes de programación**: R, Python, Perl, Bash, php, javascript.
- **High performance computing**: Manejo de clusters SGE, Amazon webservices (EC2, Glacier, EBS).
- **Otros**: R/Shiny, git, mysql, apache, UNIX, markdown, css, html.

# Cursos

- **Human Genome Tour 2016: From NGS Technologies to Evolutionary and medical Genomics**. _Institut Pasteur de Montevideo_. Duración: 120 horas. \hfill \textcolor{mygray} {2016}.
- **Genética de Poblaciones Parte II: Genética Cuantitativa**. _FCEyN - UBA, Argentina_. Docente: Juan Carlos Viladardi. Duración: 119 horas. \hfill \textcolor{mygray} {2015}.
- **Genética de Poblaciones Parte I: Caracteres Discretos**. _FCEyN - UBA, Argentina_. Docente: Juan Carlos Viladardi. Duración: 170 horas. \hfill \textcolor{mygray} {2015}.
- **Introducción al Análisis de Datos Genéticos con R**. _FCEyN - UBA, Argentina_. Docente: Juan Carlos Viladardi. Duración: 90 horas. \hfill \textcolor{mygray} {2014}.
- **RNAseq and functional annotation**. _FCEyN - UBA, Argentina_. Docente: Ana Conesa, Diego de Pannis. Duración: 24 horas. \hfill \textcolor{mygray} {2013}.
- **Assembly and Assembly Validation of NGS reads**. 2013. _CIFASIS - CONICET, Argentina_. Docente: Bernardo Clavijo. Organizado por la Sociedad Iberoamericana de Bioinformática y la Asociación Argentina de Bioinformática y Biología Computacional.
- **Lenguaje R aplicado a la Bioinformática**. _CIFASIS - CONICET, Argentina_. Workshop organizado por el RSG-Argentina. Facultad de Ingeniería, Universidad de Entre Ríos. \hfill \textcolor{mygray} {2012}.